theme: jekyll-theme-minimal
title: BananaFalls's homepage
description: Work in progress!

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
